security:
    enable_authenticator_manager: true

    providers:
        app_user_provider:
            id: App\Security\UserProvider

    firewalls:
        main:
            pattern: ^/
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\JwtAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        - { path: ^/documents, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/$, roles: PUBLIC_ACCESS  }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10 